tls:
  certificates:
    - certFile: ./cert.pem
      keyFile: ./privkey.pem


http:
  # Add the router
  routers:
    api:
      rule: "PathPrefix(`/`)"
      service: api@internal
      entryPoints:
      - "traefikapi"

    trtpost:
      entryPoints:
      - "ep0"
      middlewares:
      - my-basic-auth
      - cors
      service: service-foo
      rule: "Host(`trt2.btmc.live`) && !Method(`GET`)"
      priority: 9999
      tls: {}

    trtapi:
      entryPoints:
        - "ep0"
      middlewares:
        - cors
      service: service-foo
      rule: "Host(`trt2.btmc.live`)"
      priority: 1
      tls: {}

  # Add the middleware
  middlewares:
    my-basic-auth:
      basicAuth:
        users:
        - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
        - soundboard:$apr1$9vgsw1td$q/yOJRLqJTeGDKF.V0EEf1
        # About 220,000,000 results (0.50 seconds)
        - soundboard:$apr1$oks19fh5$HbhebmYEi8qdTl9W/yOH/1

        # https://discord.com/channels/@me/261053355793580032/1124503967032938567
        - trt2api:$apr1$2dqv79xz$Uzp3Oc25eQRA9y1v9nc9x.

    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlAllowHeaders: "*"
        accessControlAllowOriginList:
          - "*"

  services:
    service-foo:
      loadBalancer:
        servers:
        - url: http://127.0.0.1:5280/
        passHostHeader: false
